### ISSUE TITLE
Problem compilig in ubuntu 15.04

### ISSUE THREAD

**Issue by pastukhov** [cmusphinx/node-pocketsphinx#10]
Hi
I'm getting
```
node-pocketsphinx$ npm install

> pocketsphinx@1.0.1 install /home/artem/build/ps/node-pocketsphinx
> node-gyp rebuild

make: вход в каталог «/home/artem/build/ps/node-pocketsphinx/build»
  CXX(target) Release/obj.target/PocketSphinx/src/Factory.o
  CXX(target) Release/obj.target/PocketSphinx/src/Recognizer.o
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::AddKeyphraseSearch(const v8::Arguments&)’:
../src/Recognizer.cpp:109:64: error: ‘ps_set_keyphrase’ was not declared in this scope
   int result = ps_set_keyphrase(instance->ps, *name, *keyphrase);
                                                                ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::AddKeywordsSearch(const v8::Arguments&)’:
../src/Recognizer.cpp:133:53: error: ‘ps_set_kws’ was not declared in this scope
   int result = ps_set_kws(instance->ps, *name, *file);
                                                     ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::AddGrammarSearch(const v8::Arguments&)’:
../src/Recognizer.cpp:157:59: error: ‘ps_set_jsgf_file’ was not declared in this scope
   int result = ps_set_jsgf_file(instance->ps, *name, *file);
                                                           ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::AddNgramSearch(const v8::Arguments&)’:
../src/Recognizer.cpp:181:57: error: ‘ps_set_lm_file’ was not declared in this scope
   int result = ps_set_lm_file(instance->ps, *name, *file);
                                                         ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::GetSearch(v8::Local<v8::String>, const v8::AccessorInfo&)’:
../src/Recognizer.cpp:191:69: error: ‘ps_get_search’ was not declared in this scope
   Local<Value> search = String::NewSymbol(ps_get_search(instance->ps));
                                                                     ^
../src/Recognizer.cpp: In static member function ‘static void Recognizer::SetSearch(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::AccessorInfo&)’:
../src/Recognizer.cpp:201:38: error: ‘ps_set_search’ was not declared in this scope
   ps_set_search(instance->ps, *search);
                                      ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::Start(const v8::Arguments&)’:
../src/Recognizer.cpp:207:41: error: too few arguments to function ‘int ps_start_utt(ps_decoder_t*, const char*)’
   int result = ps_start_utt(instance->ps);
                                         ^
In file included from ../src/Recognizer.h:7:0,
                 from ../src/Recognizer.cpp:2:
/usr/local/include/pocketsphinx/pocketsphinx.h:363:5: note: declared here
 int ps_start_utt(ps_decoder_t *ps, char const *uttid);
     ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::Restart(const v8::Arguments&)’:
../src/Recognizer.cpp:227:41: error: too few arguments to function ‘int ps_start_utt(ps_decoder_t*, const char*)’
   int result = ps_start_utt(instance->ps);
                                         ^
In file included from ../src/Recognizer.h:7:0,
                 from ../src/Recognizer.cpp:2:
/usr/local/include/pocketsphinx/pocketsphinx.h:363:5: note: declared here
 int ps_start_utt(ps_decoder_t *ps, char const *uttid);
     ^
../src/Recognizer.cpp: In static member function ‘static v8::Handle<v8::Value> Recognizer::WriteSync(const v8::Arguments&)’:
../src/Recognizer.cpp:290:52: error: too few arguments to function ‘const char* ps_get_hyp(ps_decoder_t*, int32*, const char**)’
   const char* hyp = ps_get_hyp(instance->ps, &score);
                                                    ^
In file included from ../src/Recognizer.h:7:0,
                 from ../src/Recognizer.cpp:2:
/usr/local/include/pocketsphinx/pocketsphinx.h:449:13: note: declared here
 char const *ps_get_hyp(ps_decoder_t *ps, int32 *out_best_score,
             ^
../src/Recognizer.cpp: In static member function ‘static void Recognizer::AsyncWorker(uv_work_t*)’:
../src/Recognizer.cpp:308:58: error: too few arguments to function ‘const char* ps_get_hyp(ps_decoder_t*, int32*, const char**)’
   const char* hyp = ps_get_hyp(data->instance->ps, &score);
                                                          ^
In file included from ../src/Recognizer.h:7:0,
                 from ../src/Recognizer.cpp:2:
/usr/local/include/pocketsphinx/pocketsphinx.h:449:13: note: declared here
 char const *ps_get_hyp(ps_decoder_t *ps, int32 *out_best_score,
             ^
PocketSphinx.target.mk:87: ошибка выполнения рецепта для цели «Release/obj.target/PocketSphinx/src/Recognizer.o»
make: *** [Release/obj.target/PocketSphinx/src/Recognizer.o] Ошибка 1
make: выход из каталога «/home/artem/build/ps/node-pocketsphinx/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-21-lowlatency
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/artem/build/ps/node-pocketsphinx
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 

npm ERR! pocketsphinx@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@1.0.1 install script.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-21-lowlatency
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/artem/build/ps/node-pocketsphinx
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/artem/build/ps/node-pocketsphinx/npm-debug.log
npm ERR! not ok code 0
```

**Comment by nshmyrev** [comment]
You need to install pocketsphinx and sphinxbase from github, you have an older version.

**Comment by pastukhov** [comment]
Ok
