### ISSUE TITLE
Still problem to install on MAC OS X 10.11.2 and node v5.3.0

### ISSUE THREAD

**Issue by mk-conn** [cmusphinx/node-pocketsphinx#12]
PKG_CONFIG_PATH is set to /usr/local/lib/pkginfo

running npm install results in:

```
> pocketsphinx@5.0.0 install /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx
> node-gyp -v rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/5.3.0/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   '-v',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.0.3
gyp info using node@5.3.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.3.0
gyp verb command install [ '5.3.0' ]
gyp verb install input version string "5.3.0"
gyp verb install installing version: 5.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.3.0
gyp verb build dir attempting to create "build" dir: /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx/build
gyp verb build dir "build" dir needed to be created? /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx/config.gypi
gyp verb common.gypi checking for gypi file: /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mk/.node-gyp/5.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mk/.node-gyp/5.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/mk/.node-gyp/5.3.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/PocketSphinx/wrap_ps.o', needed by `Release/PocketSphinx.node'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /Users/mk/PhpstormProjects/pocketsphinx-test/node_modules/pocketsphinx
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON pocketsphinx-test@0.0.1 No repository field.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.0 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pocketsphinx@5.0.0 install script 'node-gyp -v rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp -v rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mk/PhpstormProjects/pocketsphinx-test/npm-debug.log

```

Pocketsphinx and sphinxbase are present in /usr/local/lib/pkginfo (installed with brew). 
Don't really know what else I could do to make the install work?

**Comment by nshmyrev** [comment]
You need to run update.sh before building the module from git. You also should have swig installed.

**Comment by nshmyrev** [comment]
Also, you need to install pocketsphinx and sphinxbase from git master, not from any older versions

**Comment by mk-conn** [comment]
which update.sh? Is there a guide somewhere on how to install the package since an easy npm install will not work?

**Comment by nshmyrev** [comment]
I have updated the code and also published to npm, please try again

**Comment by mk-conn** [comment]
Worked like a charm :) Thank you!
