### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by pvantrepote** [cmusphinx/node-pocketsphinx#14]
Hi,

The build always failed and have no idea on how to fix it.
It looks like a version issue between node and node-gyp.
I tried to downgrade the node version but no success, any ides on how to solve it?

Thanks,

```javascript
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /Users/XXXXXX/Downloads/cmu/node-pocketsphinx
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! pocketsphinx@5.0.3 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.3 install script 'node-gyp -v rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp -v rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.
```

**Comment by nshmyrev** [comment]
You need to read (and provide in issue) the full build log. The real problem is just few lines above the line you pasted.
