### ISSUE TITLE
npm install fails with node 7.2

### ISSUE THREAD

**Issue by 821760408-sp** [cmusphinx/node-pocketsphinx#37]
Hi,

I have the latest sphinxbase and pocketsphinx installed from github, also PKG_CONFIG_PATH is set to /usr/local/lib/pkgconfig.

I have cmake of version 3.7.1 and SWIG of Version 3.0.10.

When I tried to do npm install pocketsphinx it gave the following error:

[log.txt](https://github.com/cmusphinx/node-pocketsphinx/files/628564/log.txt)

Seemed to be a problem with "cmake-js compile" ?

**Comment by nshmyrev** [comment]
What is your node version?

**Comment by 821760408-sp** [comment]
node version is 7.2.0
npm is 3.10.9

**Comment by nshmyrev** [comment]
Swig does not support node 7 yet, see for details https://github.com/swig/swig/issues/825

You could try node 5 or, probably, wait till the swig issue is resolved.

**Comment by kate008** [comment]
I try to use the Pocketsphinx in my nodejs project while installing this I am getting this error

pm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

Please,help me to solve this error.

Thanks in advance.

**Comment by dnyaneshwar1991** [comment]
Hi,
I have installed all required libraries, but when I try to execute example code given for js I got following error

module.js:471
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jjadhad/nodejs/test.js:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Please help

**Comment by nshmyrev** [comment]
Latest PR is at https://github.com/swig/swig/pull/968

**Comment by highvoltage379** [comment]
I managed to install node-pocketsphinx with node version 9.0.0 (should work with 7.x and 8.x as well).
These pull request https://github.com/swig/swig/pull/968 corrects the bug. Apparently, they don't want to merge with master yet, but it works.

(I had some trouble in finding the actual repo that contains the pull request, here's the link: https://github.com/swig/swig/tree/f08d7a63a92a3ba89d97bdfcc206e1e1c4804c0f)
