### ISSUE TITLE
module.js:471 throw err;

### ISSUE THREAD

**Issue by dnyaneshwar1991** [cmusphinx/node-pocketsphinx#42]
Hi,
I have installed all required libraries for node-pocketsphinx,
But when I try to execute example code I got following error
module.js:471
    throw err;
    ^

Error: Cannot find module 'pocketsphinx'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jjadhad/nodejs/test.js:3:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

please help

**Comment by nshmyrev** [comment]
You need to follow the instructions in README and build pocketsphinx module properly. You also need to watch for errors in build process.
