### ISSUE TITLE
Cannot make sense of install process

### ISSUE THREAD

**Issue by Mykasoda** [cmusphinx/node-pocketsphinx#57]
Greetings,

Thank you for providing this great tool, it seems to be the only one that does what I'm looking to implement.

I followed the installation guide as provided in the readme, but I'm a bit unclear as to how to finalize the process.

I am getting this error...

` node test.js
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/PocketSphinx.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/soda/Documents/pocketsphinx/index.js:1:82)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

But I think the bigger problem is that I just don't know what to do to run the program. Am I supposed to run it with Node? I know seems like such a noob question, but I'm coming from using WebKit which is native, and not used to setting up something like this.

Thanks so much for any advice.

**Comment by Mykasoda** [comment]
I also get `FATAL: "continuous.c", line 158: Failed to open file 'goforward.raw' for reading: No such file or directory`

when I run pocketsphinx_continuous -infile goforward.raw

soooo I'm for sure doing something wrong, but cannot figure out for the life of me what it is :-P
