### ISSUE TITLE
Installation process in ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [cmusphinx/node-pocketsphinx#6]
sudo git clone https://github.com/cmusphinx/node-pocketsphinx.git
cd node-pocketsphinx
npm install
node index.js

this error show me:

	module.js:340
		throw err;
			  ^
	Error: Cannot find module './build/Release/PocketSphinx.node'
		at Function.Module._resolveFilename (module.js:338:15)
		at Function.Module._load (module.js:280:25)
		at Module.require (module.js:364:17)
		at require (module.js:380:17)
		at Object.<anonymous> (/home/felipe/node-pocketsphinx/index.js:1:82)
		at Module._compile (module.js:456:26)
		at Object.Module._extensions..js (module.js:474:10)
		at Module.load (module.js:356:32)
		at Function.Module._load (module.js:312:12)
		at Function.Module.runMain (module.js:497:10)

**Comment by nshmyrev** [comment]
Most likely there were build issues during compilation, you need to study (and provide) the full log, not just the last error.
